version: '3.8'

services:
  contest-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - PORT=3001
      - NEXT_PUBLIC_MAIN_APP_URL=${NEXT_PUBLIC_MAIN_APP_URL:-https://sacavia.com}
      - NEXT_PUBLIC_CONTEST_APP_URL=${NEXT_PUBLIC_CONTEST_APP_URL:-https://vote.sacavia.com}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-https://sacavia.com/api}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - contest-network

  # Development service (optional)
  contest-app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3002:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - NEXT_PUBLIC_MAIN_APP_URL=${NEXT_PUBLIC_MAIN_APP_URL:-https://sacavia.com}
      - NEXT_PUBLIC_CONTEST_APP_URL=${NEXT_PUBLIC_CONTEST_APP_URL:-https://vote.sacavia.com}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-https://sacavia.com/api}
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    restart: unless-stopped
    networks:
      - contest-network
    profiles:
      - dev

networks:
  contest-network:
    driver: bridge

volumes:
  contest-logs:
